### 마일스톤 등록
POST /api/projects/1/milestones
Host: localhost:9090
Content-Type: application/json

{
  "name": "마일스톤1",
  "startDate": "2023-04-28",
  "endDate": "2023-06-01"
}

### 마일스톤 수정
PUT /api/projects/1/milestones/2
Host: localhost:9090
Content-Type: application/json

{
  "name": "마일스톤 수정",
  "startDate": "2023-04-29",
  "endDate": "2023-06-01"
}

### 마일스톤 삭제
DELETE /api/projects/1/milestones/1
Host: localhost:9090
Content-Type: application/json
