### 프로젝트 등록
POST /api/projects
Host: localhost:9090
Content-Type: application/json

{
  "name": "프로젝트 이름",
  "description": "프로젝트 설명",
  "memberId": 1,
  "memberName": "홍길동"
}


### 프로젝트 수정 (기본설정)
PUT /api/projects/1
Host: localhost:9090
Content-Type: application/json

{
  "status": "휴면",
  "name": "프로젝트 이름 수정",
  "description": "프로젝트 설명 수정"
}


### 프로젝트 삭제
DELETE /api/projects/1
Host: localhost:9090
Content-Type: application/json


### 프로젝트 멤버 등록
POST /api/projects/1/members
Host: localhost:9090
Content-Type: application/json

{
  "memberId": 2,
  "memberName": "김조원",
  "role": "멤버"
}


### 프로젝트 멤버 역할 수정
PUT /api/projects/1/members/2
Host: localhost:9090
Content-Type: application/json

{
  "role": "관리자"
}

### 프로젝트 멤버 삭제
DELETE /api/projects/17/members/2
Host: localhost:9090
Content-Type: application/json


### 멤버 아이다로 프로젝트 리스트 조회
GET /api/projects/members/1
Host: localhost:9090
Content-Type: application/json


### 프로젝트 아이디로 프로젝트 조회
GET /api/projects/1
Host: localhost:9090
Content-Type: application/json